#!/usr/bin/env python3
"""Zero-dependency regression tests for legacy instruction normalization."""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
SOURCE_KIT = REPO_ROOT / "omnigento"
GENERATED_MARKER = "<!-- GENERATED BY omnigento/bin/sync_ai_instructions.py; DO NOT EDIT DIRECTLY -->"
LEGACY_GENERATED_MARKER = "<!-- GENERATED BY instruction-seed/bin/sync_ai_instructions.py; DO NOT EDIT DIRECTLY -->"
BEGIN_BLOCK = "<!-- BEGIN GENERATED INSTRUCTIONS -->"
END_BLOCK = "<!-- END GENERATED INSTRUCTIONS -->"


class RegressionError(AssertionError):
    pass


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def read_json(path: Path) -> object:
    return json.loads(path.read_text(encoding="utf-8"))


def copy_kit(target: Path) -> None:
    kit = target / "omnigento"
    kit.mkdir(parents=True, exist_ok=True)
    shutil.copy2(SOURCE_KIT / "HOW_TO_RUN.md", kit / "HOW_TO_RUN.md")
    for name in ["bin", "lib", "meta", "docs"]:
        shutil.copytree(SOURCE_KIT / name, kit / name)


def run(repo: Path, *args: str, expect_ok: bool = True) -> subprocess.CompletedProcess[str]:
    cmd = [sys.executable, "omnigento/bin/normalize_legacy_instructions.py", *args]
    result = subprocess.run(cmd, cwd=repo, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False)
    if expect_ok and result.returncode != 0:
        raise RegressionError(
            f"command failed: {' '.join(cmd)}\nstdout:\n{result.stdout}\nstderr:\n{result.stderr}"
        )
    if not expect_ok and result.returncode == 0:
        raise RegressionError(f"command unexpectedly passed: {' '.join(cmd)}\nstdout:\n{result.stdout}")
    return result


def run_sync(repo: Path, *args: str, expect_ok: bool = True) -> subprocess.CompletedProcess[str]:
    cmd = [sys.executable, "omnigento/bin/sync_ai_instructions.py", *args]
    result = subprocess.run(cmd, cwd=repo, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False)
    if expect_ok and result.returncode != 0:
        raise RegressionError(
            f"command failed: {' '.join(cmd)}\nstdout:\n{result.stdout}\nstderr:\n{result.stderr}"
        )
    if not expect_ok and result.returncode == 0:
        raise RegressionError(f"command unexpectedly passed: {' '.join(cmd)}\nstdout:\n{result.stdout}")
    return result


def role_counts(repo: Path, run_id: str) -> dict[str, int]:
    inventory = read_json(repo / "omnigento" / ".tmp" / "normalize" / run_id / "inventory.json")
    counts: dict[str, int] = {}
    if not isinstance(inventory, list):
        raise RegressionError("inventory.json must be a list")
    for record in inventory:
        role = record["role"]
        counts[role] = counts.get(role, 0) + 1
    return counts


def manifest(repo: Path, run_id: str) -> dict[str, object]:
    value = read_json(repo / "omnigento" / ".tmp" / "normalize" / run_id / "manifest.json")
    if not isinstance(value, dict):
        raise RegressionError("manifest.json must be an object")
    return value


def assert_equal(actual: object, expected: object, label: str) -> None:
    if actual != expected:
        raise RegressionError(f"{label}: expected {expected!r}, got {actual!r}")


def assert_contains(text: str, needle: str, label: str) -> None:
    if needle not in text:
        raise RegressionError(f"{label}: expected output to contain {needle!r}\n{text}")


def assert_not_contains(text: str, needle: str, label: str) -> None:
    if needle in text:
        raise RegressionError(f"{label}: expected output not to contain {needle!r}\n{text}")


def create_normalized_project(repo: Path) -> None:
    copy_kit(repo)
    write(
        repo / ".github" / "instructions" / "example.instructions.md",
        """---
description: "Example topic."
---

# Example
""",
    )
    write(
        repo / ".github" / "instructions" / "skills" / "example-skill.instructions.md",
        """---
description: "Example skill."
---

# Example Skill
""",
    )
    write(
        repo / "AGENTS.md",
        f"""{GENERATED_MARKER}

# Project
""",
    )
    write(
        repo / "CLAUDE.md",
        f"""{GENERATED_MARKER}

# Project
""",
    )
    write(
        repo / ".cursor" / "rules" / "example.mdc",
        f"""---
globs: "**/*.py"
alwaysApply: false
---
{GENERATED_MARKER}
""",
    )
    write(repo / ".claude" / "rules" / "example.md", f"{GENERATED_MARKER}\n\n# Example\n")
    write(
        repo / ".github" / "copilot-instructions.md",
        f"""# Project AI Instructions

{BEGIN_BLOCK}

| File | Covers | Auto-loads for |
|------|--------|----------------|

{END_BLOCK}
""",
    )


def test_normalized_project_noop(base: Path) -> None:
    repo = base / "normalized-project"
    create_normalized_project(repo)
    run_id = "normalized-noop"

    run(repo, "--inventory", "--run-id", run_id)
    counts = role_counts(repo, run_id)
    assert_equal(counts.get("legacy_input", 0), 0, "normalized legacy_input count")
    assert_equal(counts.get("canonical", 0), 2, "normalized canonical count")

    run(repo, "--classify", "--run-id", run_id, "--runtime", "mock")
    run(repo, "--merge", "--run-id", run_id)
    run(repo, "--propose", "--run-id", run_id)
    run(repo, "--apply", "--run-id", run_id)
    data = manifest(repo, run_id)
    assert_equal(data.get("classified_count"), 0, "normalized classified count")
    assert_equal(data.get("proposed_file_count"), 0, "normalized proposed count")
    assert_equal(data.get("applied_file_count"), 0, "normalized applied count")


def test_legacy_generated_markers_not_legacy_input(base: Path) -> None:
    repo = base / "legacy-generated-markers"
    create_normalized_project(repo)
    for path in [
        repo / "AGENTS.md",
        repo / "CLAUDE.md",
        repo / ".cursor" / "rules" / "example.mdc",
        repo / ".claude" / "rules" / "example.md",
    ]:
        text = path.read_text(encoding="utf-8").replace(GENERATED_MARKER, LEGACY_GENERATED_MARKER)
        path.write_text(text, encoding="utf-8")

    run_id = "legacy-generated-markers"
    run(repo, "--inventory", "--run-id", run_id)
    counts = role_counts(repo, run_id)
    assert_equal(counts.get("legacy_input", 0), 0, "legacy marker legacy_input count")
    assert_equal(counts.get("generated_output", 0), 5, "legacy marker generated_output count")


def write_fixture_classifier(repo: Path) -> Path:
    classifier = repo / "fixture_classifier.py"
    write(
        classifier,
        r'''#!/usr/bin/env python3
import json
import sys

task = json.load(sys.stdin)
source = task["source_path"]
rules = []
discarded = []
conflicts = []

if source == "GEMINI.md":
    rules.append({
        "text": "Never deploy directly to production. Production changes must go through test first.",
        "topic": "legacy-normalize-safety-test",
        "scope": "topic-based",
        "glob": None,
        "kind": "safety",
        "confidence": "high",
        "sources": [source],
        "source_quote": "Never deploy directly to production. Production changes must go through test first.",
    })
    rules.append({
        "text": "C# plugin edits require // EDIT: markers with reason and date.",
        "topic": "legacy-normalize-plugin-test",
        "scope": "file-scoped",
        "glob": "**/*.cs",
        "kind": "style",
        "confidence": "high",
        "sources": [source],
        "source_quote": "C# plugin edits require // EDIT markers.",
    })
elif source == ".windsurfrules":
    rules.append({
        "text": "Never deploy directly to production. Production changes must go through test first.",
        "topic": "legacy-normalize-safety-test",
        "scope": "topic-based",
        "glob": None,
        "kind": "safety",
        "confidence": "medium",
        "sources": [source],
        "source_quote": "Production deploys must go through test first and never be done directly.",
    })
    rules.append({
        "text": "Root provider files should point at canonical instructions.",
        "topic": "legacy-normalize-root-test",
        "scope": "root-only",
        "glob": None,
        "kind": "provider",
        "confidence": "medium",
        "sources": [source],
        "source_quote": "Root provider files should point at canonical instructions.",
    })
    conflicts.append("Legacy files use different wording for production deployment.")
    discarded.append({
        "text": "Read this file first.",
        "reason": "provider boilerplate",
        "source_quote": "Read this file first.",
    })

json.dump({
    "source_path": task["source_path"],
    "surface_id": task["surface_id"],
    "owner": task["owner"],
    "surface_kind": task["surface_kind"],
    "source_sha256": task["source_sha256"],
    "runtime": "fixture",
    "status": "classified",
    "durable_rules": rules,
    "discarded": discarded,
    "conflicts": conflicts,
    "notes": ["fixture classifier"],
}, sys.stdout)
''',
    )
    classifier.chmod(0o755)
    return classifier


def create_legacy_overlap_project(repo: Path) -> Path:
    copy_kit(repo)
    write(
        repo / "GEMINI.md",
        """# Gemini Legacy Instructions

- Never deploy directly to production. Production changes must go through test first.
- C# plugin edits require // EDIT: markers with reason and date.
""",
    )
    write(
        repo / ".windsurfrules",
        """# Windsurf Legacy Rules

- Production deploys must go through test first and never be done directly.
- Root provider files should point at canonical instructions.
""",
    )
    return write_fixture_classifier(repo)


def write_status_classifier(repo: Path, status: str) -> Path:
    classifier = repo / f"{status}_classifier.py"
    write(
        classifier,
        f'''#!/usr/bin/env python3
import json
import sys

task = json.load(sys.stdin)
json.dump({{
    "source_path": task["source_path"],
    "surface_id": task["surface_id"],
    "owner": task["owner"],
    "surface_kind": task["surface_kind"],
    "source_sha256": task["source_sha256"],
    "runtime": "fixture",
    "status": "{status}",
    "durable_rules": [],
    "discarded": [],
    "conflicts": [],
    "notes": []
}}, sys.stdout)
''',
    )
    classifier.chmod(0o755)
    return classifier


def write_single_rule_classifier(repo: Path) -> Path:
    classifier = repo / "single_rule_classifier.py"
    write(
        classifier,
        r'''#!/usr/bin/env python3
import json
import sys

task = json.load(sys.stdin)
source = task["source_path"]
json.dump({
    "source_path": source,
    "surface_id": task["surface_id"],
    "owner": task["owner"],
    "surface_kind": task["surface_kind"],
    "source_sha256": task["source_sha256"],
    "runtime": "fixture",
    "status": "classified",
    "durable_rules": [{
        "text": "Never deploy directly to production.",
        "topic": "legacy-normalize-symlink-test",
        "scope": "topic-based",
        "glob": None,
        "kind": "safety",
        "confidence": "high",
        "sources": [source],
        "source_quote": "Never deploy directly to production.",
    }],
    "discarded": [],
    "conflicts": [],
    "notes": []
}, sys.stdout)
''',
    )
    classifier.chmod(0o755)
    return classifier


def create_single_legacy_project(repo: Path) -> Path:
    copy_kit(repo)
    write(repo / "GEMINI.md", "# Legacy\n\n- Never deploy directly to production.\n")
    return write_single_rule_classifier(repo)


def create_sync_project(repo: Path) -> None:
    copy_kit(repo)
    write(
        repo / ".github" / "instructions" / "topic.instructions.md",
        """---
description: "Topic rule."
---

# Topic

Use this topic.
""",
    )
    write(
        repo / ".github" / "instructions" / "scoped.instructions.md",
        """---
description: "Scoped rule."
applyTo: "src/**"
---

# Scoped

Use this scoped rule.
""",
    )
    write(
        repo / ".github" / "instructions" / "skills" / "action.instructions.md",
        """---
description: "Action rule."
---

# Action

Use this action.
""",
    )
    write(repo / ".gitignore", ".DS_Store\nThumbs.db\n")


def test_sync_audit_clean_project(base: Path) -> None:
    repo = base / "sync-audit-clean"
    create_sync_project(repo)

    run_sync(repo, "--write")
    run_sync(repo, "--check")
    audit = run_sync(repo, "--audit")
    if "audit passed" not in audit.stdout:
        raise RegressionError("clean sync audit did not pass")


def test_sync_audit_rejects_orphan_cursor_rule(base: Path) -> None:
    repo = base / "sync-audit-orphan-cursor"
    create_sync_project(repo)

    run_sync(repo, "--write")
    write(
        repo / ".cursor" / "rules" / "orphan.mdc",
        f"""---
description: "Orphan."
alwaysApply: false
---
{GENERATED_MARKER}
""",
    )

    audit = run_sync(repo, "--audit", expect_ok=False)
    assert_contains(audit.stdout, "orphan-provider-pointer", "orphan Cursor rule audit failure")


def test_sync_audit_rejects_skill_in_topic_index(base: Path) -> None:
    repo = base / "sync-audit-skill-in-topic-index"
    create_sync_project(repo)

    run_sync(repo, "--write")
    topic_index = repo / ".cursor" / "rules" / "topic-index.mdc"
    with topic_index.open("a", encoding="utf-8") as handle:
        handle.write("- **Action rule** -> `.github/instructions/skills/action.instructions.md`\n")

    audit = run_sync(repo, "--audit", expect_ok=False)
    assert_contains(audit.stdout, "on-request-misclassified", "skill topic-index audit failure")


def test_sync_audit_rejects_missing_skill_views(base: Path) -> None:
    repo = base / "sync-audit-missing-skill-views"
    create_sync_project(repo)

    run_sync(repo, "--write")
    (repo / ".cursor" / "rules" / "action.mdc").unlink()
    (repo / ".claude" / "skills" / "action" / "SKILL.md").unlink()

    audit = run_sync(repo, "--audit", expect_ok=False)
    assert_contains(audit.stdout, "missing-provider-view", "missing skill provider view audit failure")
    assert_contains(audit.stdout, ".cursor/rules/action.mdc", "missing Cursor skill view audit failure")
    assert_contains(audit.stdout, ".claude/skills/action/SKILL.md", "missing Claude skill view audit failure")


def test_sync_audit_rejects_orphan_claude_outputs(base: Path) -> None:
    repo = base / "sync-audit-orphan-claude"
    create_sync_project(repo)

    run_sync(repo, "--write")
    write(
        repo / ".claude" / "rules" / "orphan.md",
        f"""{GENERATED_MARKER}

# Orphan
""",
    )
    write(
        repo / ".claude" / "skills" / "orphan" / "SKILL.md",
        f"""---
name: orphan
description: orphan
---
{GENERATED_MARKER}
""",
    )

    audit = run_sync(repo, "--audit", expect_ok=False)
    assert_contains(audit.stdout, ".claude/rules/orphan.md", "orphan Claude rule audit failure")
    assert_contains(audit.stdout, ".claude/skills/orphan/SKILL.md", "orphan Claude skill audit failure")
    assert_contains(audit.stdout, "orphan-provider-pointer", "orphan Claude output audit failure")


def test_sync_audit_rejects_frontmatter_drift(base: Path) -> None:
    repo = base / "sync-audit-frontmatter-drift"
    create_sync_project(repo)

    run_sync(repo, "--write")
    topic_index = repo / ".cursor" / "rules" / "topic-index.mdc"
    topic_index.write_text(topic_index.read_text(encoding="utf-8").replace("---\nalwaysApply: false\n---", "---\nglobs: \"\"\nalwaysApply: true\n---"), encoding="utf-8")

    scoped_rule = repo / ".cursor" / "rules" / "scoped.mdc"
    scoped_rule.write_text(scoped_rule.read_text(encoding="utf-8").replace('globs: "src/**"', 'globs: "wrong/**"'), encoding="utf-8")

    action_rule = repo / ".cursor" / "rules" / "action.mdc"
    action_rule.write_text(action_rule.read_text(encoding="utf-8").replace("description: \"Action rule.\"", "description: \"Action rule.\"\nglobs: \"**/*\""), encoding="utf-8")

    claude_topic = repo / ".claude" / "rules" / "topic-index.md"
    claude_topic.write_text("---\ntitle: bad\n---\n" + claude_topic.read_text(encoding="utf-8"), encoding="utf-8")

    audit = run_sync(repo, "--audit", expect_ok=False)
    assert_contains(audit.stdout, "frontmatter-drift", "frontmatter drift audit failure")
    assert_contains(audit.stdout, ".cursor/rules/topic-index.mdc", "Cursor topic-index frontmatter audit failure")
    assert_contains(audit.stdout, ".cursor/rules/scoped.mdc", "file-scoped Cursor globs audit failure")
    assert_contains(audit.stdout, ".cursor/rules/action.mdc", "on-request Cursor globs audit failure")
    assert_contains(audit.stdout, ".claude/rules/topic-index.md", "Claude topic-index frontmatter audit failure")


def test_sync_audit_rejects_agents_and_hub_coverage_drift(base: Path) -> None:
    repo = base / "sync-audit-coverage-drift"
    create_sync_project(repo)

    run_sync(repo, "--write")
    agents = repo / "AGENTS.md"
    agents.write_text(agents.read_text(encoding="utf-8").replace("Topic rule", "Changed topic rule"), encoding="utf-8")

    copilot = repo / ".github" / "copilot-instructions.md"
    copilot.write_text(copilot.read_text(encoding="utf-8").replace("](.github/instructions/topic.instructions.md)", "](.github/instructions/missing-topic.instructions.md)"), encoding="utf-8")

    audit = run_sync(repo, "--audit", expect_ok=False)
    assert_contains(audit.stdout, "index-wording-drift", "AGENTS index wording audit failure")
    assert_contains(audit.stdout, "hub-coverage-gap", "Copilot hub coverage audit failure")


def test_sync_audit_rejects_missing_nested_agents(base: Path) -> None:
    repo = base / "sync-audit-missing-nested-agents"
    create_sync_project(repo)

    run_sync(repo, "--write")
    (repo / "src" / "AGENTS.md").unlink()

    audit = run_sync(repo, "--audit", expect_ok=False)
    assert_contains(audit.stdout, "generated-missing", "missing nested AGENTS audit failure")
    assert_contains(audit.stdout, "src/AGENTS.md", "missing nested AGENTS path audit failure")


def test_sync_audit_dangling_link_edges(base: Path) -> None:
    repo = base / "sync-audit-dangling-link-edges"
    create_sync_project(repo)

    write(
        repo / ".github" / "copilot-instructions.md",
        """# Test Project - AI Instructions

External link is fine: [OpenAI](https://openai.com).
Anchor link is fine: [Local](#local).
Inline code is ignored: `[Broken](missing-inline.md)`.

```text
[Broken](missing-fenced.md)
```

## Reference Docs

<!-- BEGIN GENERATED INSTRUCTIONS -->
<!-- END GENERATED INSTRUCTIONS -->
""",
    )
    run_sync(repo, "--write")
    audit = run_sync(repo, "--audit")
    assert_contains(audit.stdout, "audit passed", "non-local and fenced links audit pass")

    with (repo / ".github" / "copilot-instructions.md").open("a", encoding="utf-8") as handle:
        handle.write("\nReal missing link: [Broken](missing-real.md)\n")

    audit = run_sync(repo, "--audit", expect_ok=False)
    assert_contains(audit.stdout, "dangling-reference", "real dangling link audit failure")
    assert_contains(audit.stdout, "missing-real.md", "real dangling link audit target")
    assert_not_contains(audit.stdout, "missing-inline.md", "inline code link ignored")
    assert_not_contains(audit.stdout, "missing-fenced.md", "fenced link ignored")


def test_sync_audit_json_failure_output(base: Path) -> None:
    repo = base / "sync-audit-json-failure"
    create_sync_project(repo)

    run_sync(repo, "--write")
    write(
        repo / ".cursor" / "rules" / "orphan.mdc",
        f"""---
description: "Orphan."
alwaysApply: false
---
{GENERATED_MARKER}
""",
    )

    audit = run_sync(repo, "--audit", "--json", expect_ok=False)
    findings = json.loads(audit.stdout)
    if not any(finding.get("code") == "orphan-provider-pointer" for finding in findings):
        raise RegressionError("JSON audit failure output did not include orphan-provider-pointer")


def test_sync_audit_warnings_only_exit_zero(base: Path) -> None:
    repo = base / "sync-audit-warnings-only"
    create_sync_project(repo)

    run_sync(repo, "--write")
    write(repo / ".gitignore", "")

    audit = run_sync(repo, "--audit")
    assert_contains(audit.stdout, "WARN gitignore-hygiene", "warnings-only audit output")


def test_sync_write_audit_repairs_generated_drift(base: Path) -> None:
    repo = base / "sync-write-audit-repairs-generated-drift"
    create_sync_project(repo)

    run_sync(repo, "--write")
    write(
        repo / ".cursor" / "rules" / "orphan.mdc",
        f"""---
description: "Orphan."
alwaysApply: false
---
{GENERATED_MARKER}
""",
    )
    agents = repo / "AGENTS.md"
    agents.write_text(agents.read_text(encoding="utf-8") + "\n[Broken](missing.md)\n", encoding="utf-8")

    repaired = run_sync(repo, "--write", "--audit")
    assert_contains(repaired.stdout, "removed stale generated files", "write audit stale cleanup")
    assert_contains(repaired.stdout, "instruction integrity audit passed", "write audit repaired generated drift")


def test_legacy_overlap_pipeline(base: Path) -> None:
    repo = base / "legacy-overlap"
    classifier = create_legacy_overlap_project(repo)
    run_id = "legacy-overlap"

    run(repo, "--inventory", "--run-id", run_id)
    counts = role_counts(repo, run_id)
    assert_equal(counts.get("legacy_input", 0), 2, "legacy overlap input count")

    run(
        repo,
        "--classify",
        "--run-id",
        run_id,
        "--runtime",
        "command",
        "--classifier-command",
        f"{sys.executable} {classifier}",
    )
    run(repo, "--merge", "--run-id", run_id)
    run(repo, "--propose", "--run-id", run_id)

    data = manifest(repo, run_id)
    assert_equal(data.get("classified_count"), 2, "legacy classified count")
    assert_equal(data.get("merged_rule_count"), 3, "legacy merged count")
    assert_equal(data.get("conflict_count"), 1, "legacy conflict count")
    assert_equal(data.get("discarded_count"), 1, "legacy discarded count")
    assert_equal(data.get("proposed_file_count"), 2, "legacy proposed count")
    assert_equal(data.get("unsupported_rule_count"), 1, "legacy unsupported count")

    refused = run(repo, "--apply", "--run-id", run_id, expect_ok=False)
    if "unsupported rules" not in refused.stderr:
        raise RegressionError("apply refusal did not mention unsupported rules")

    run(repo, "--apply", "--run-id", run_id, "--allow-unsupported")
    assert (repo / ".github" / "instructions" / "legacy-normalize-safety-test.instructions.md").is_file()
    assert (repo / ".github" / "instructions" / "legacy-normalize-plugin-test.instructions.md").is_file()
    data = manifest(repo, run_id)
    assert_equal(data.get("applied_file_count"), 2, "legacy applied count")


def test_invalid_classifier_status_rejected(base: Path) -> None:
    repo = base / "invalid-classifier-status"
    copy_kit(repo)
    write(repo / "GEMINI.md", "# Legacy\n\n- Never deploy directly to production.\n")
    classifier = write_status_classifier(repo, "banana")
    run_id = "invalid-classifier-status"

    run(repo, "--inventory", "--run-id", run_id)
    refused = run(
        repo,
        "--classify",
        "--run-id",
        run_id,
        "--runtime",
        "command",
        "--classifier-command",
        f"{sys.executable} {classifier}",
        expect_ok=False,
    )
    if "status" not in refused.stderr:
        raise RegressionError("invalid classifier status rejection did not mention status")


def test_apply_rejects_symlink_source(base: Path) -> None:
    repo = base / "apply-symlink-source"
    classifier = create_single_legacy_project(repo)
    run_id = "apply-symlink-source"

    run(repo, "--inventory", "--run-id", run_id)
    run(
        repo,
        "--classify",
        "--run-id",
        run_id,
        "--runtime",
        "command",
        "--classifier-command",
        f"{sys.executable} {classifier}",
    )
    run(repo, "--merge", "--run-id", run_id)
    run(repo, "--propose", "--run-id", run_id)

    proposed_file = (
        repo
        / "omnigento"
        / ".tmp"
        / "normalize"
        / run_id
        / "proposed"
        / ".github"
        / "instructions"
        / "legacy-normalize-symlink-test.instructions.md"
    )
    outside = repo / "outside.instructions.md"
    write(outside, "---\ndescription: escaped\n---\n")
    proposed_file.unlink()
    proposed_file.symlink_to(outside)

    refused = run(repo, "--apply", "--run-id", run_id, expect_ok=False)
    if "symlink" not in refused.stderr:
        raise RegressionError("symlink source rejection did not mention symlink")


def test_run_id_traversal_rejected(base: Path) -> None:
    repo = base / "run-id-traversal"
    copy_kit(repo)
    refused = run(repo, "--inventory", "--run-id", "../escape", expect_ok=False)
    if "run id" not in refused.stderr:
        raise RegressionError("run id traversal rejection did not mention run id")


def test_setup_entrypoint_ux(base: Path) -> None:
    del base
    how_to_run = (SOURCE_KIT / "HOW_TO_RUN.md").read_text(encoding="utf-8")
    setup = SOURCE_KIT / "docs" / "setup.md"
    plant = (SOURCE_KIT / "bin" / "plant.py").read_text(encoding="utf-8")

    assert_equal(how_to_run.strip(), "# How To Run\n\nRead and follow `omnigento/docs/setup.md`.", "HOW_TO_RUN")
    if not setup.is_file():
        raise RegressionError("setup.md entrypoint is missing")
    assert_contains(plant, "Read and follow omnigento/docs/setup.md", "plant next step")
    assert_not_contains(plant, "Copy the prompt", "plant stale copy prompt")
    assert_not_contains(plant, "paste it into your AI assistant", "plant stale paste prompt")


def test_core_templates_do_not_force_project_opinions(base: Path) -> None:
    del base
    setup = (SOURCE_KIT / "docs" / "setup.md").read_text(encoding="utf-8")
    omnigento = (SOURCE_KIT / "docs" / "omnigento.instructions.md").read_text(encoding="utf-8")
    plant = (SOURCE_KIT / "bin" / "plant.py").read_text(encoding="utf-8")

    assert_not_contains(setup, "`ai-behavior`, `documentation-rules`", "setup core topics")
    assert_not_contains(omnigento, "Every code file MUST have a matching `.md` file.", "core documentation opinion")
    assert_not_contains(plant, "ai-behavior.instructions.md", "plant skeleton ai behavior link")
    assert_contains(omnigento, "omnigento/custom-instructions/", "custom instruction support")


def main() -> int:
    tests = [
        ("setup_entrypoint_ux", test_setup_entrypoint_ux),
        ("core_templates_do_not_force_project_opinions", test_core_templates_do_not_force_project_opinions),
        ("normalized_project_noop", test_normalized_project_noop),
        ("legacy_generated_markers_not_legacy_input", test_legacy_generated_markers_not_legacy_input),
        ("legacy_overlap_pipeline", test_legacy_overlap_pipeline),
        ("invalid_classifier_status_rejected", test_invalid_classifier_status_rejected),
        ("apply_rejects_symlink_source", test_apply_rejects_symlink_source),
        ("run_id_traversal_rejected", test_run_id_traversal_rejected),
        ("sync_audit_clean_project", test_sync_audit_clean_project),
        ("sync_audit_rejects_orphan_cursor_rule", test_sync_audit_rejects_orphan_cursor_rule),
        ("sync_audit_rejects_skill_in_topic_index", test_sync_audit_rejects_skill_in_topic_index),
        ("sync_audit_rejects_missing_skill_views", test_sync_audit_rejects_missing_skill_views),
        ("sync_audit_rejects_orphan_claude_outputs", test_sync_audit_rejects_orphan_claude_outputs),
        ("sync_audit_rejects_frontmatter_drift", test_sync_audit_rejects_frontmatter_drift),
        ("sync_audit_rejects_agents_and_hub_coverage_drift", test_sync_audit_rejects_agents_and_hub_coverage_drift),
        ("sync_audit_rejects_missing_nested_agents", test_sync_audit_rejects_missing_nested_agents),
        ("sync_audit_dangling_link_edges", test_sync_audit_dangling_link_edges),
        ("sync_audit_json_failure_output", test_sync_audit_json_failure_output),
        ("sync_audit_warnings_only_exit_zero", test_sync_audit_warnings_only_exit_zero),
        ("sync_write_audit_repairs_generated_drift", test_sync_write_audit_repairs_generated_drift),
    ]
    with tempfile.TemporaryDirectory(prefix="omnigento-regression-") as temp:
        base = Path(temp)
        for name, test in tests:
            try:
                test(base)
            except Exception as exc:
                print(f"FAIL {name}: {exc}", file=sys.stderr)
                return 1
            print(f"PASS {name}")
    print(f"PASS {len(tests)} regression tests")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
