"""Known AI instruction surfaces for legacy instruction normalization."""

from __future__ import annotations

from dataclasses import dataclass


GENERATED_MARKER = "<!-- GENERATED BY omnigento/bin/sync_ai_instructions.py; DO NOT EDIT DIRECTLY -->"
LEGACY_GENERATED_MARKERS = (
    "<!-- GENERATED BY instruction-seed/bin/sync_ai_instructions.py; DO NOT EDIT DIRECTLY -->",
)
GENERATED_MARKERS = (GENERATED_MARKER, *LEGACY_GENERATED_MARKERS)
GENERATED_BLOCK_BEGIN = "<!-- BEGIN GENERATED INSTRUCTIONS -->"
GENERATED_BLOCK_END = "<!-- END GENERATED INSTRUCTIONS -->"
SCAFFOLD_MARKER = "<!-- omnigento scaffold -->"
LEGACY_SCAFFOLD_MARKERS = ("<!-- instruction-seed scaffold -->",)
SCAFFOLD_MARKERS = (SCAFFOLD_MARKER, *LEGACY_SCAFFOLD_MARKERS)


@dataclass(frozen=True)
class InstructionSurface:
    """A provider or convention-specific place where AI instructions may live."""

    id: str
    display_name: str
    owner: str
    surface_kind: str
    legacy_input_patterns: tuple[str, ...] = ()
    generated_output_patterns: tuple[str, ...] = ()
    canonical_patterns: tuple[str, ...] = ()
    can_scan_legacy: bool = True
    can_generate: bool = False
    parser_hint: str = ""
    boilerplate_patterns: tuple[str, ...] = ()

    @property
    def scan_patterns(self) -> tuple[tuple[str, str], ...]:
        """Return patterns paired with their registry role."""

        items: list[tuple[str, str]] = []
        items.extend((pattern, "canonical") for pattern in self.canonical_patterns)
        items.extend((pattern, "generated_output") for pattern in self.generated_output_patterns)
        items.extend((pattern, "legacy_input") for pattern in self.legacy_input_patterns)
        return tuple(items)


INSTRUCTION_SURFACES: tuple[InstructionSurface, ...] = (
    InstructionSurface(
        id="omnigento-canonical",
        display_name="Omnigento Canonical",
        owner="omnigento",
        surface_kind="canonical",
        canonical_patterns=(
            ".github/instructions/*.instructions.md",
            ".github/instructions/skills/*.instructions.md",
        ),
        can_scan_legacy=False,
        can_generate=False,
        parser_hint="Canonical Omnigento topic or on-request skill.",
    ),
    InstructionSurface(
        id="copilot-hub",
        display_name="GitHub Copilot Hub",
        owner="copilot",
        surface_kind="root-hub",
        legacy_input_patterns=(".github/copilot-instructions.md",),
        generated_output_patterns=(".github/copilot-instructions.md",),
        can_generate=True,
        parser_hint="Provider-neutral hub table plus global project rules.",
        boilerplate_patterns=("read and follow", "source of truth", "reference docs"),
    ),
    InstructionSurface(
        id="cursor-rules",
        display_name="Cursor Rules",
        owner="cursor",
        surface_kind="rules",
        legacy_input_patterns=(".cursor/rules/*.mdc",),
        generated_output_patterns=(".cursor/rules/*.mdc",),
        can_generate=True,
        parser_hint="Cursor MDC rules. Frontmatter may contain globs, description, and alwaysApply.",
    ),
    InstructionSurface(
        id="cursor-legacy-root",
        display_name="Cursor Legacy Root Rule",
        owner="cursor",
        surface_kind="legacy-root",
        legacy_input_patterns=(".cursorrules",),
        can_generate=False,
        parser_hint="Legacy Cursor root rule file.",
    ),
    InstructionSurface(
        id="claude-root",
        display_name="Claude Root",
        owner="claude",
        surface_kind="root",
        legacy_input_patterns=("CLAUDE.md",),
        generated_output_patterns=("CLAUDE.md",),
        can_generate=True,
        parser_hint="Claude Code root instructions.",
        boilerplate_patterns=("read and follow", "canonical source", "source of truth"),
    ),
    InstructionSurface(
        id="claude-nested-root",
        display_name="Claude Nested Root",
        owner="claude",
        surface_kind="nested-root",
        legacy_input_patterns=("**/CLAUDE.md",),
        can_generate=False,
        parser_hint="Directory-scoped Claude instructions.",
    ),
    InstructionSurface(
        id="claude-rules",
        display_name="Claude Rules",
        owner="claude",
        surface_kind="rules",
        legacy_input_patterns=(".claude/rules/*.md",),
        generated_output_patterns=(".claude/rules/*.md",),
        can_generate=True,
        parser_hint="Claude rule file. Frontmatter may contain paths.",
    ),
    InstructionSurface(
        id="claude-skills",
        display_name="Claude Skills",
        owner="claude",
        surface_kind="skills",
        legacy_input_patterns=(".claude/skills/*/SKILL.md",),
        generated_output_patterns=(".claude/skills/*/SKILL.md",),
        can_generate=True,
        parser_hint="Claude skill. Frontmatter may contain name and description.",
    ),
    InstructionSurface(
        id="agent-markdown-root",
        display_name="Agent Markdown Root",
        owner="agent-markdown",
        surface_kind="root",
        legacy_input_patterns=("AGENTS.md",),
        generated_output_patterns=("AGENTS.md",),
        can_generate=True,
        parser_hint="Root AGENTS.md shared by tools that read the agent-markdown convention.",
        boilerplate_patterns=("read and follow", "canonical source", "source of truth"),
    ),
    InstructionSurface(
        id="agent-markdown-nested",
        display_name="Agent Markdown Nested",
        owner="agent-markdown",
        surface_kind="nested-root",
        legacy_input_patterns=("**/AGENTS.md",),
        generated_output_patterns=("**/AGENTS.md",),
        can_generate=True,
        parser_hint="Directory-scoped AGENTS.md.",
    ),
    InstructionSurface(
        id="gemini-root",
        display_name="Gemini Root",
        owner="gemini",
        surface_kind="root",
        legacy_input_patterns=("GEMINI.md",),
        can_generate=False,
        parser_hint="Gemini CLI root instructions.",
    ),
    InstructionSurface(
        id="windsurf-root",
        display_name="Windsurf Root",
        owner="windsurf",
        surface_kind="root",
        legacy_input_patterns=(".windsurfrules",),
        can_generate=False,
        parser_hint="Windsurf root instruction file.",
    ),
    InstructionSurface(
        id="cline-root",
        display_name="Cline Root",
        owner="cline",
        surface_kind="root",
        legacy_input_patterns=(".clinerules",),
        can_generate=False,
        parser_hint="Cline root instruction file.",
    ),
    InstructionSurface(
        id="roo-rules",
        display_name="Roo Rules",
        owner="roo",
        surface_kind="rules",
        legacy_input_patterns=(".roo/rules/**",),
        can_generate=False,
        parser_hint="Roo rule files.",
    ),
    InstructionSurface(
        id="cody",
        display_name="Cody",
        owner="cody",
        surface_kind="rules",
        legacy_input_patterns=(".cody/**",),
        can_generate=False,
        parser_hint="Cody instruction or context files.",
    ),
)


SURFACES_BY_ID: dict[str, InstructionSurface] = {surface.id: surface for surface in INSTRUCTION_SURFACES}
